//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yedekparcacim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isletme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Isletme()
        {
            this.UrunKayit = new HashSet<UrunKayit>();
        }
    
        public int isletmeId { get; set; }
        public string adres { get; set; }
        public string isletmeIsim { get; set; }
        public string kategori { get; set; }
        public string mail { get; set; }
        public string parola { get; set; }
        public string TelNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunKayit> UrunKayit { get; set; }
    }
}
