//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yedekparcacim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunKayit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UrunKayit()
        {
            this.Favoriler = new HashSet<Favoriler>();
        }
    
        public int urunId { get; set; }
        public string aracmarka { get; set; }
        public string durum { get; set; }
        public string marka { get; set; }
        public int ucret { get; set; }
        public string urunisim { get; set; }
        public int isletmeurunId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favoriler> Favoriler { get; set; }
        public virtual Isletme Isletme { get; set; }
    }
}
